### PR TITLE
Allow setting of host/refreshInterval using url parameters.

### PR DESCRIPTION
**Pull request by olimcc**
Useful if you're not hosting the plugin with your cluster.

The commit looks larger than it is simply because of some excess whitespace that was in the file - let me know if this is a problem!

### CODE REVIEW

**Comment by polyfractal** [comment]
Does this cover a use-case that the "change host" button doesn't?  Or is it just a convenience flag so you don't have to change the host each time (e.g. just bookmark the URI)?

(NP about the whitespace, happy those are gone anyhow :) )

**Comment by olimcc** [comment]
It's primarily a convenience if you don't host the plugin with elasticsearch but still want to be able to link directly to an immediately working set of charts, without requiring people to input anything (both cases are true for me!). Where I work we have a url shortening service, so it's convenient to be able to put these settings in a url and have it just work.

I use [bigdesk](https://github.com/lukas-vlcek/bigdesk/blob/master/README.textile#url-parameters) in a similar way so to some extent was just mimicking what they provided.

**Comment by polyfractal** [comment]
Sounds perfectly reasonable to me, thanks for the explanation!  Merging right now

**Comment by olimcc** [comment]
Thanks Zachary! Great tool, now I can share the fun!

**Pull request merged**
